{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fg.secretName" . }}
  namespace: {{ include "fg.namespace" . }}
  labels:
    {{- include "fg.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "fg.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: fg-internal-tokens
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.internalToken }}
    - secretKey: postgres-password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.postgresPassword }}
    - secretKey: oidc-issuer-url
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.oidcIssuerUrl }}
    - secretKey: oidc-audience
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.oidcAudience }}
    - secretKey: decision-anchor-s3-bucket
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.s3Bucket }}
{{- end }}
