{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fg-sidecar-hpa
  namespace: {{ include "fg.namespace" . }}
  labels:
    {{- include "fg.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fg-sidecar
  minReplicas: {{ .Values.hpa.sidecar.minReplicas }}
  maxReplicas: {{ .Values.hpa.sidecar.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.sidecar.targetCPUUtilization }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fg-gateway-hpa
  namespace: {{ include "fg.namespace" . }}
  labels:
    {{- include "fg.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fg-gateway
  minReplicas: {{ .Values.hpa.gateway.minReplicas }}
  maxReplicas: {{ .Values.hpa.gateway.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.gateway.targetCPUUtilization }}
{{- end }}
