apiVersion: v1
kind: Secret
metadata:
  name: fg-internal
  namespace: {{ include "fg.namespace" . }}
  labels:
    {{- include "fg.labels" . | nindent 4 }}
stringData:
  fg-internal-tokens: {{ .Values.internalToken | quote }}
