apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: modelgovernor
resources:
  - ../../base
patches:
  - path: patch-replicas.yaml
  - path: patch-hpa.yaml
  - path: gateway-loadbalancer.yaml
images:
  - name: ghcr.io/mc8h7dxz6t-ui/modelgovernor-sidecar
    newTag: v0.1.0
  - name: ghcr.io/mc8h7dxz6t-ui/modelgovernor-reconciler
    newTag: v0.1.0
