apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

patchesStrategicMerge:
  - patch-configmap.yaml
  - patch-sidecar-deployment.yaml
  - patch-reconciler-deployment.yaml

images:
  - name: modelgovernor/sidecar
    newTag: staging
  - name: modelgovernor/reconciler
    newTag: staging
