apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: modelgovernor

resources:
  - ../../base
  - egress-istio.yaml
  - mtls-mesh.yaml

patches:
  - path: istio-injection-patches.yaml
