apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: modelgovernor
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: modelgovernor-mtls
  namespace: modelgovernor
spec:
  host: "*.modelgovernor.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: sidecar-mtls
  namespace: modelgovernor
spec:
  host: sidecar.modelgovernor.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: gateway-mtls
  namespace: modelgovernor
spec:
  host: gateway.modelgovernor.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: reconciler-mtls
  namespace: modelgovernor
spec:
  host: reconciler.modelgovernor.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
