"""Image promotion manifest — build, tag, and Helm overlay generation."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


@dataclass(frozen=True)
class PromotedImage:
    key: str
    name: str
    dockerfile: str
    registry_ref: str
    immutable_tag: str
    env_tag: str


def load_manifest(manifest_path: Path | None = None) -> dict[str, Any]:
    path = manifest_path or Path(__file__).resolve().parents[2] / "scripts" / "image-promotion.manifest.yaml"
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or "governors" not in data:
        raise ValueError(f"invalid image promotion manifest: {path}")
    return data


def manifest_conformance_failures(repo_root: Path | None = None) -> list[str]:
    root = repo_root or Path(__file__).resolve().parents[2]
    failures: list[str] = []
    manifest = load_manifest(root / "scripts" / "image-promotion.manifest.yaml")
    for gov_key, spec in manifest["governors"].items():
        ctx = root / spec.get("build_context", ".")
        for entry in spec.get("images", []):
            dockerfile = root / entry["dockerfile"]
            if not dockerfile.is_file():
                failures.append(f"{gov_key}: missing dockerfile {entry['dockerfile']}")
            if not entry.get("name") or not entry.get("key"):
                failures.append(f"{gov_key}: image entry missing name/key")
        if not (root / spec["helm_chart"]).is_dir():
            failures.append(f"{gov_key}: helm chart missing at {spec['helm_chart']}")
    return failures


def normalize_registry(registry: str) -> str:
    return registry.rstrip("/").lower()


def image_tags(*, git_sha: str, environment: str) -> tuple[str, str]:
    sha = git_sha.strip().lower()
    short = sha[:12]
    immutable = f"sha-{sha}"
    env_tag = f"{environment}-{short}"
    return immutable, env_tag


def registry_image(registry: str, image_name: str, tag: str) -> str:
    reg = normalize_registry(registry)
    name = image_name.lstrip("/").lower()
    return f"{reg}/{name}:{tag}"


def build_promotion_plan(
    *,
    governor: str,
    registry: str,
    git_sha: str,
    environment: str,
    repo_root: Path | None = None,
) -> dict[str, Any]:
    root = repo_root or Path(__file__).resolve().parents[2]
    manifest = load_manifest(root / "scripts" / "image-promotion.manifest.yaml")
    governors = manifest["governors"]
    if governor == "all":
        keys = list(governors.keys())
    else:
        alias = {
            "mg": "modelgovernor",
            "fg": "finance-governor",
            "ig": "insurance-governor",
            "cg": "cybersecurity-governor",
        }.get(governor, governor)
        if alias not in governors:
            raise ValueError(f"unknown governor: {governor}")
        keys = [alias]

    immutable_tag, env_tag = image_tags(git_sha=git_sha, environment=environment)
    plan_governors: dict[str, Any] = {}
    for key in keys:
        spec = governors[key]
        images: list[dict[str, str]] = []
        for entry in spec["images"]:
            name = entry["name"]
            images.append(
                {
                    "key": entry["key"],
                    "name": name,
                    "dockerfile": entry["dockerfile"],
                    "context": spec.get("build_context", "."),
                    "immutable_ref": registry_image(registry, name, immutable_tag),
                    "env_ref": registry_image(registry, name, env_tag),
                }
            )
        plan_governors[key] = {
            "helm_chart": spec["helm_chart"],
            "helm_values_style": spec["helm_values_style"],
            "images": images,
        }

    return {
        "governor": governor,
        "environment": environment,
        "registry": normalize_registry(registry),
        "git_sha": git_sha,
        "immutable_tag": immutable_tag,
        "env_tag": env_tag,
        "governors": plan_governors,
    }


def render_helm_values_overlay(plan: dict[str, Any], governor_key: str) -> str:
    spec = plan["governors"][governor_key]
    tag = plan["immutable_tag"]
    registry = plan["registry"]
    style = spec["helm_values_style"]
    lines: list[str] = [
        "# Generated by image promotion — do not edit by hand",
        f"# git_sha: {plan['git_sha']}",
        f"# environment: {plan['environment']}",
        "",
    ]
    if style == "split":
        lines.append("images:")
        for img in spec["images"]:
            full_repo = f"{registry}/{img['name'].lower()}"
            lines.append(f"  {img['key']}:")
            lines.append(f'    repository: "{full_repo}"')
            lines.append(f'    tag: "{tag}"')
            lines.append("    pullPolicy: Always")
    elif style == "combined":
        lines.append("image:")
        lines.append("  pullPolicy: Always")
        for img in spec["images"]:
            ref = registry_image(registry, img["name"], tag)
            lines.append(f'  {img["key"]}: "{ref}"')
    else:
        raise ValueError(f"unsupported helm_values_style: {style}")
    return "\n".join(lines) + "\n"


def write_promotion_artifacts(plan: dict[str, Any], out_dir: Path) -> dict[str, str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, str] = {}
    manifest_path = out_dir / "promotion-plan.json"
    manifest_path.write_text(json.dumps(plan, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    paths["plan"] = str(manifest_path)
    env = plan["environment"]
    for gov_key in plan["governors"]:
        overlay = render_helm_values_overlay(plan, gov_key)
        overlay_path = out_dir / f"{gov_key}-{env}-images.yaml"
        overlay_path.write_text(overlay, encoding="utf-8")
        paths[f"helm-{gov_key}"] = str(overlay_path)
    return paths
