apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finance-governor

resources:
  - ../../helm/finance-governor

commonLabels:
  environment: production

patches:
  - target:
      kind: Deployment
      name: fg-sidecar
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: fg-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

configMapGenerator:
  - name: fg-env-overlay
    literals:
      - FG_ENV=production
      - OTEL_SERVICE_NAME=financegovernor-sidecar
