apiVersion: v1
kind: Service
metadata:
  name: {{ include "modelgovernor.fullname" . }}-gateway
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "modelgovernor.labels" . | nindent 4 }}
    app: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    {{- include "modelgovernor.selectorLabels" . | nindent 4 }}
    app: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.port }}
