apiVersion: v1
kind: Service
metadata:
  name: {{ include "modelgovernor.fullname" . }}-reconciler
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "modelgovernor.labels" . | nindent 4 }}
    app: reconciler
spec:
  type: ClusterIP
  selector:
    {{- include "modelgovernor.selectorLabels" . | nindent 4 }}
    app: reconciler
  ports:
    - name: http
      port: {{ .Values.reconciler.port }}
      targetPort: {{ .Values.reconciler.port }}
