{{- if .Values.sidecar.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "modelgovernor.fullname" . }}-sidecar
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "modelgovernor.labels" . | nindent 4 }}
    app: sidecar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "modelgovernor.fullname" . }}-sidecar
  minReplicas: {{ .Values.sidecar.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sidecar.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.sidecar.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.sidecar.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
