apiVersion: v1
kind: Service
metadata:
  name: {{ include "modelgovernor.fullname" . }}-sidecar
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "modelgovernor.labels" . | nindent 4 }}
    app: sidecar
spec:
  type: ClusterIP
  selector:
    {{- include "modelgovernor.selectorLabels" . | nindent 4 }}
    app: sidecar
  ports:
    - name: http
      port: {{ .Values.sidecar.port }}
      targetPort: {{ .Values.sidecar.port }}
