apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sidecar-egress
  namespace: modelgovernor
spec:
  podSelector:
    matchLabels:
      app: sidecar
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
