apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - sidecar-deployment.yaml
  - sidecar-service.yaml
  - reconciler-deployment.yaml
  - migration-job.yaml
