apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cybersecuritygovernor

resources:
  - namespace.yaml
  - configmap.yaml
  - cg-sidecar-deployment.yaml
  - cg-gateway-deployment.yaml
  - cg-reconciler-deployment.yaml
  - network-policy.yaml
  - security-chain-verify-cronjob.yaml
  - security-chain-anchor-cronjob.yaml
  - prometheus-rules.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: cybersecuritygovernor
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
