apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sidecar
  namespace: modelgovernor
spec:
  minReplicas: 4
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
