sidecar:
  replicas: 2
  hpa:
    minReplicas: 2
    maxReplicas: 6

gateway:
  replicas: 1

reconciler:
  replicas: 1

postgres:
  enabled: true

secrets:
  create: false

externalSecrets:
  enabled: false

syntheticProbe:
  enabled: true
