apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - externalsecret.yaml

patches:
  - target:
      kind: Secret
      name: cybersecuritygovernor-secrets
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: cybersecuritygovernor-secrets
        namespace: cybersecuritygovernor
  - target:
      kind: Deployment
      name: cg-sidecar
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: ConfigMap
      name: cybersecuritygovernor-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cybersecuritygovernor-config
        namespace: cybersecuritygovernor
      data:
        OIDC_ENABLED: "true"
        GATEWAY_OIDC_ENABLED: "true"
        SECURITY_ANCHOR_S3_OBJECT_LOCK_ENABLED: "true"
  - target:
      kind: Deployment
      name: cg-gateway
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cg-gateway
        namespace: cybersecuritygovernor
      spec:
        template:
          spec:
            containers:
              - name: cg-gateway
                env:
                  - name: OIDC_ISSUER_URL
                    valueFrom:
                      secretKeyRef:
                        name: cybersecuritygovernor-secrets
                        key: oidc-issuer-url
                  - name: OIDC_AUDIENCE
                    valueFrom:
                      secretKeyRef:
                        name: cybersecuritygovernor-secrets
                        key: oidc-audience
