apiVersion: apps/v1
kind: Deployment
metadata:
  name: cg-pgbouncer
  namespace: cybersecuritygovernor
spec:
  template:
    spec:
      containers:
        - name: pgbouncer
          volumeMounts:
            - name: config
              mountPath: /etc/pgbouncer/pgbouncer.ini
              subPath: pgbouncer.ini
            - name: cg-pgbouncer-auth
              mountPath: /etc/pgbouncer/userlist.txt
              subPath: userlist.txt
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: cg-pgbouncer-config
        - name: cg-pgbouncer-auth
          secret:
            secretName: cybersecuritygovernor-pgbouncer-auth
