apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: modelgovernor-gitops
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: modelgovernor
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mc8h7dxz6t-ui/modelgovernor.v01
    targetRevision: main
    path: deploy/argocd
    directory:
      exclude: '{application-gitops.yaml,README.md}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
