#!/usr/bin/env bash
# Generate production-grade secrets for Cybersecurity Governor.
# Usage:
#   ./scripts/bootstrap-secrets.sh              # print to stdout
#   ./scripts/bootstrap-secrets.sh --write-env  # write cyber-governor/.env
#   ./scripts/bootstrap-secrets.sh --write-k8s  # write deploy/generated/secrets.yaml
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT}/.env"
ENV_EXAMPLE="${ROOT}/.env.example"
GENERATED_DIR="${ROOT}/deploy/generated"
K8S_SECRETS="${GENERATED_DIR}/secrets.yaml"
VAULT_KEYS="${GENERATED_DIR}/secret-manager-keys.json"

WRITE_ENV=false
WRITE_K8S=false

for arg in "$@"; do
  case "$arg" in
    --write-env) WRITE_ENV=true ;;
    --write-k8s) WRITE_K8S=true ;;
    -h|--help)
      sed -n '2,6p' "$0"
      exit 0
      ;;
    *) echo "Unknown arg: $arg" >&2; exit 1 ;;
  esac
done

rand_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    python3 -c "import secrets; print(secrets.token_hex(32))"
  fi
}

CG_TOKEN="$(rand_hex)"
PG_PASSWORD="${POSTGRES_PASSWORD:-$(rand_hex | cut -c1-24)}"
PG_USER="${POSTGRES_USER:-postgres}"
PG_DB="${POSTGRES_DB:-cybersecuritygovernor}"
S3_BUCKET="${SECURITY_ANCHOR_S3_BUCKET:-your-corp-security-anchor}"

DATABASE_URL="postgresql+psycopg://${PG_USER}:${PG_PASSWORD}@cg-postgres:5432/${PG_DB}"
DATABASE_URL_DIRECT="postgresql://${PG_USER}:${PG_PASSWORD}@cg-postgres:5432/${PG_DB}"
REDIS_URL="${REDIS_URL:-redis://cg-redis:6379/0}"

emit_env() {
  cat <<EOF
# Generated by bootstrap-secrets.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
POSTGRES_DB=${PG_DB}
POSTGRES_USER=${PG_USER}
POSTGRES_PASSWORD=${PG_PASSWORD}

CG_SIDECAR_URL=http://localhost:8101
CG_GATEWAY_URL=http://localhost:8100
CG_INTERNAL_TOKENS=${CG_TOKEN}
CG_SPINE_ENABLED=true

SECURITY_ANCHOR_S3_BUCKET=${S3_BUCKET}
SECURITY_ANCHOR_S3_PREFIX=security-anchors
EOF
}

emit_k8s_secret() {
  cat <<EOF
# Generated by bootstrap-secrets.sh — apply once: kubectl apply -f deploy/generated/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cybersecuritygovernor-secrets
  namespace: cybersecuritygovernor
type: Opaque
stringData:
  database-url: ${DATABASE_URL}
  database-url-direct: ${DATABASE_URL_DIRECT}
  redis-url: ${REDIS_URL}
  cg-internal-tokens: ${CG_TOKEN}
  security-anchor-s3-bucket: ${S3_BUCKET}
EOF
}

emit_vault_keys() {
  python3 - <<PY
import json
keys = {
    "cybersecuritygovernor/database-url": "${DATABASE_URL}",
    "cybersecuritygovernor/database-url-direct": "${DATABASE_URL_DIRECT}",
    "cybersecuritygovernor/redis-url": "${REDIS_URL}",
    "cybersecuritygovernor/cg-internal-tokens": "${CG_TOKEN}",
    "cybersecuritygovernor/security-anchor-s3-bucket": "${S3_BUCKET}",
    "cybersecuritygovernor/oidc-issuer-url": "https://login.example.com/",
    "cybersecuritygovernor/oidc-audience": "cybersecuritygovernor",
}
print(json.dumps(keys, indent=2))
PY
}

if [[ "$WRITE_ENV" == true ]]; then
  emit_env > "$ENV_FILE"
  echo "Wrote ${ENV_FILE}"
fi

if [[ "$WRITE_K8S" == true ]]; then
  mkdir -p "$GENERATED_DIR"
  emit_k8s_secret > "$K8S_SECRETS"
  emit_vault_keys > "$VAULT_KEYS"
  echo "Wrote ${K8S_SECRETS}"
  echo "Wrote ${VAULT_KEYS}"
fi

if [[ "$WRITE_ENV" == false && "$WRITE_K8S" == false ]]; then
  echo "=== .env ==="
  emit_env
  echo ""
  echo "=== secret-manager-keys.json (upload to vault) ==="
  emit_vault_keys
fi
