{{- if .Values.monitoring.sidecarPodMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sidecar
  namespace: {{ include "modelgovernor.namespace" . }}
  labels:
    {{- include "modelgovernor.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector:
    matchLabels:
      app: sidecar
  podMetricsEndpoints:
    - port: http
      path: /metrics/prometheus
      interval: 30s
{{- end }}
{{- if .Values.monitoring.reconcilerPodMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: reconciler
  namespace: {{ include "modelgovernor.namespace" . }}
  labels:
    {{- include "modelgovernor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: reconciler
  podMetricsEndpoints:
    - port: http-health
      path: /metrics/prometheus
      interval: 30s
{{- end }}
