{{- if .Values.migrations.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrations-bundle
  namespace: {{ include "insurancegovernor.namespace" . }}
  labels:
    {{- include "insurancegovernor.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
{{- range $path, $content := .Files.Glob "files/migrations/*.sql" }}
  {{ base $path }}: |
{{ $content | toString | indent 4 }}
{{- end }}
{{- end }}
