apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "insurancegovernor.namespace" . }}
  labels:
    {{- include "insurancegovernor.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
