apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cybersecuritygovernor

resources:
  - ../../base
  - egress-istio.yaml
  - mtls-mesh.yaml
  - spine-authz-istio.yaml

patches:
  - path: istio-injection-patches.yaml
